<a href="https://colab.research.google.com/github/hsieh2000/HW/blob/main/%E8%AC%9D%E5%A4%A9%E9%9D%92_TNL%20Data%20Analyst%20Intern_test3_Python_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

資料說明
請從 TNL Data Analyst Intern_test3_R_Data.xlsx 存取資料。
某客戶提供了一筆問卷的後台收集資訊，其中變數命名如下：
1.	後台相關資訊：CollectorNm, RespondentID, CollectorID
2.	問卷開始/結束時間：StartDate, EndDate
3.	填答者電子郵件：Email
4.	q開頭的欄位則為該題的填答結果，
單選題欄位命名方式如：q0001，代表問卷的第1題。
多選題欄位命名方式如：q0002_0006，代表第2題的第6個選項的作答結果。
矩陣題欄位命名方式如：q0003_0004，代表第3題的第4小題的作答結果。
備註：矩陣題示意如下，一個大題中會詢問複數個小題，其中每個小題皆僅能選一個答案(單選)。

In [119]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [120]:
import pandas as pd
import numpy as np

In [121]:
RAW_DATA = pd.read_excel("/content/drive/MyDrive/關鍵評論網/TNL Data Analyst Intern_test3_R_Data.xlsx", sheet_name="Raw Data")

1.	因業務需求，客戶需要調出第61題的填答狀況，並加以分析。
該題要求受訪者勾選有使用的影音平台。
※此題為多選題
第1個選項為「沒有使用任何影音平台」，若勾選此選項，則該欄位標記為1，且其餘9個選項皆無法選取。
選項2~10分別為9個常見的影音平台，若使用者有勾選該平台，則標記為1。

Q1. 請算出每名受訪者有使用的平台總數，並儲存在新的變數欄位 B2_Count

In [122]:
question61_columns = [col for col, name in enumerate(RAW_DATA.columns) if "q0061" in name]
question_61 = RAW_DATA.iloc[:, question61_columns[0]:question61_columns[-1]+1]
question_61

,q0061_0001,q0061_0002,q0061_0003,q0061_0004,q0061_0005,q0061_0006,q0061_0007,q0061_0008,q0061_0009,q0061_0010
0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
1,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
3,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN
4,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...
218,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
219,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
220,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN
221,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN
222,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN

In [123]:
question_61["B2_Count"] = question_61.fillna(0).apply(lambda x : 0 if x[0] == 1 else (np.nan if sum(x) == 0 else sum(x[1:])), axis = 1)

In [124]:
question_61.head(50)

,q0061_0001,q0061_0002,q0061_0003,q0061_0004,q0061_0005,q0061_0006,q0061_0007,q0061_0008,q0061_0009,q0061_0010,B2_Count
0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0
1,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1.0
3,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,3.0
4,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,NaN,4.0
5,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,3.0
6,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
7,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0
8,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,2.0
9,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0
10,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,2.0
11,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0
12,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,3.0
13,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0
14,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,3.0
15,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
16,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0
17,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,NaN,NaN,3.0
18,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0
19,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,NaN,4.0
20,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,3.0
21,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0
22,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,3.0
23,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0
24,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,3.0
25,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,3.0
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0
29,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,3.0
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0
32,NaN,1.0,NaN,NaN,1.0,NaN,1.0,1.0,1.0,NaN,5.0
33,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
34,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,2.0
35,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,2.0
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,1.0,NaN,1.0,NaN,NaN,1.0,NaN,1.0,NaN,4.0
38,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,3.0
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,2.0
41,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,2.0
44,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0
45,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,2.0
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,NaN,NaN,1.0,1.0,1.0,NaN,1.0,NaN,NaN,NaN,4.0
48,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0
49,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0

2.	第63題詢問受訪者對於有在使用的影音平台的喜好程度，評分從0分到10分。(若該受訪者有使用A,B,C三個平台，則此題僅會詢問這三個平台的喜好程度)。
客戶想標記出有「隨意填答」疑慮的受訪者，判斷標準如下：
”Type1”：所有影音平台的喜好度都相同，例如：5,5,5
“Type2”：交錯填答，例如：1,3,1,3,1,3 或 2,4,6,4,2,4 這類填答間距相同的情形
“Type3”：超過9成的喜好度填答相同，例如：1,1,5,1,1,1,1,1,1,1

Q2. 請建立一個函式，判斷受訪者填答屬於哪一種Type，並將每位受訪者的Type儲存在新的欄位Status中。
如不屬於以上任何一種Type，請標記為”PASS”，如受訪者選取的平台不超過兩個，也標記為”PASS”

In [125]:
question63_columns = [col for col, name in enumerate(RAW_DATA.columns) if "q0063" in name]
question_63 = RAW_DATA.iloc[:, question63_columns[0]:question63_columns[-1]+1]
question_63

,q0063_0001,q0063_0002,q0063_0003,q0063_0004,q0063_0005,q0063_0006,q0063_0007,q0063_0008,q0063_0009
0,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN
1,7.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN
3,5.0,NaN,NaN,NaN,NaN,10.0,8.0,NaN,NaN
4,5.0,NaN,NaN,8.0,NaN,10.0,NaN,8.0,NaN
...,...,...,...,...,...,...,...,...,...
218,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN
219,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN
220,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN
221,9.0,NaN,NaN,NaN,NaN,9.0,NaN,9.0,NaN
222,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN

In [126]:
from collections import Counter

def Sum_dict(Dict): 
  sum = 0
  for i in Dict.keys(): 
    if i == -1:
      pass
    else:
      sum = sum + Dict[i] 
  return sum

def gap(raw):
  lst = [i for i in list(raw) if i != -1]
  gap_lst = [abs(lst[i+1]-lst[i]) for i in range(len(lst)-1)]
  return gap_lst

status_lst = []
question_63_fillna = question_63.fillna(-1)

for i in range(len(question_63_fillna)):
  counter = Counter(question_63_fillna.iloc[i])
  platform_num = question_61['B2_Count'].iloc[i]
  gap_lst = gap(question_63_fillna.iloc[i, :])
  if platform_num <= 2:
    print(f"{i} 狀態: PASS, 平台數: {platform_num}, 分數計數: {counter}, 原因: 平台數<=2, 填答資料: {list(question_63.iloc[i, :])}")
    status_lst.append("PASS")
  elif np.isnan(platform_num):
    print(f"{i} 狀態: Nan, 平台數: {platform_num}, 分數計數: {counter}, 原因: 平台數==Nan, 填答資料: {list(question_63.iloc[i, :])}")
    status_lst.append("Nan")
  elif len(counter.keys()) == 2 and platform_num == counter.get(max(counter)) and platform_num > 2:
    print(f"{i} 狀態: Type1, 平台數: {platform_num}, 分數計數: {counter}, 原因: 喜好度相同, 填答資料: {list(question_63.iloc[i, :])}")
    status_lst.append("Type1")
  elif len(set(gap_lst)) == 1 and gap_lst[0] != 0 and platform_num > 2:
    print(f"{i} 狀態: Type2, 平台數: {platform_num}, 分數計數: {counter}, 原因: 填答間距相同, 填答資料: {list(question_63.iloc[i, :])}")
    status_lst.append("Type2")
  elif counter.get(max(counter))/Sum_dict(counter) >= 0.9 and platform_num > 2:
    print(f"{i} 狀態: Type3, 平台數: {platform_num}, 分數計數: {counter}, 原因: 超過9成喜好度填答相同, 填答資料: {list(question_63.iloc[i, :])}")  
    status_lst.append("Type3")
  else:
    print(f"{i} 狀態: PASS, 平台數: {platform_num}, 分數計數: {counter}, 原因: 不屬於任何規則, 填答資料: {list(question_63.iloc[i, :])}")
    status_lst.append("PASS")

question_63["Status"] = status_lst
question_63

0 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 5.0: 2}), 原因: 平台數<=2, 填答資料: [5.0, nan, nan, nan, nan, 5.0, nan, nan, nan]
1 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 7.0: 1, 8.0: 1}), 原因: 平台數<=2, 填答資料: [7.0, nan, nan, nan, nan, 8.0, nan, nan, nan]
2 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 10.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, nan, 10.0, nan, nan]
3 狀態: PASS, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 5.0: 1, 10.0: 1, 8.0: 1}), 原因: 不屬於任何規則, 填答資料: [5.0, nan, nan, nan, nan, 10.0, 8.0, nan, nan]
4 狀態: PASS, 平台數: 4.0, 分數計數: Counter({-1.0: 5, 8.0: 2, 5.0: 1, 10.0: 1}), 原因: 不屬於任何規則, 填答資料: [5.0, nan, nan, 8.0, nan, 10.0, nan, 8.0, nan]
5 狀態: Type1, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 8.0: 3}), 原因: 喜好度相同, 填答資料: [8.0, nan, nan, 8.0, nan, 8.0, nan, nan, nan]
6 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 10.0: 1}), 原因: 平台數<=2, 填答資料: [10.0, nan, nan, nan, nan, nan, nan, nan, nan]
7 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 4.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 4.0, nan, nan, nan]
8 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 10.0: 1, 9.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 10.0, nan, 9.0, nan]
9 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 10.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 10.0, nan, nan, nan]
10 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 5.0: 1, 10.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 5.0, nan, 10.0, nan]
11 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 4.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 4.0, nan, nan, nan]
12 狀態: PASS, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 3.0: 1, 8.0: 1, 10.0: 1}), 原因: 不屬於任何規則, 填答資料: [3.0, nan, nan, nan, nan, 8.0, nan, 10.0, nan]
13 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 10.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 10.0, nan, nan, nan]
14 狀態: PASS, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 5.0: 1, 10.0: 1, 7.0: 1}), 原因: 不屬於任何規則, 填答資料: [5.0, nan, nan, nan, nan, 10.0, nan, 7.0, nan]
15 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 5.0: 1}), 原因: 平台數<=2, 填答資料: [5.0, nan, nan, nan, nan, nan, nan, nan, nan]
16 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 4.0: 1, 6.0: 1}), 原因: 平台數<=2, 填答資料: [4.0, nan, nan, nan, nan, 6.0, nan, nan, nan]
17 狀態: PASS, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 7.0: 2, 9.0: 1}), 原因: 不屬於任何規則, 填答資料: [7.0, nan, nan, 7.0, nan, 9.0, nan, nan, nan]
18 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 8.0: 2}), 原因: 平台數<=2, 填答資料: [8.0, nan, nan, nan, nan, 8.0, nan, nan, nan]
19 狀態: PASS, 平台數: 4.0, 分數計數: Counter({-1.0: 5, 7.0: 2, 9.0: 1, 8.0: 1}), 原因: 不屬於任何規則, 填答資料: [7.0, nan, nan, nan, nan, 9.0, 7.0, 8.0, nan]
20 狀態: PASS, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 7.0: 2, 0.0: 1}), 原因: 不屬於任何規則, 填答資料: [0.0, nan, nan, nan, nan, 7.0, nan, 7.0, nan]
21 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 8.0: 2}), 原因: 平台數<=2, 填答資料: [8.0, nan, nan, nan, nan, 8.0, nan, nan, nan]
22 狀態: PASS, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 5.0: 1, 9.0: 1, 6.0: 1}), 原因: 不屬於任何規則, 填答資料: [5.0, nan, nan, nan, nan, 9.0, nan, 6.0, nan]
23 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 10.0: 1, 7.0: 1}), 原因: 平台數<=2, 填答資料: [10.0, nan, nan, nan, nan, 7.0, nan, nan, nan]
24 狀態: Type1, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 8.0: 3}), 原因: 喜好度相同, 填答資料: [8.0, nan, nan, nan, nan, 8.0, nan, 8.0, nan]
25 狀態: Type1, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 10.0: 3}), 原因: 喜好度相同, 填答資料: [10.0, nan, nan, nan, nan, 10.0, nan, 10.0, nan]
26 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
27 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
28 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 7.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 7.0, nan, nan, nan]
29 狀態: Type1, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 7.0: 3}), 原因: 喜好度相同, 填答資料: [7.0, nan, nan, nan, nan, 7.0, nan, 7.0, nan]
30 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
31 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 10.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 10.0, nan, nan, nan]
32 狀態: Type1, 平台數: 5.0, 分數計數: Counter({10.0: 5, -1.0: 4}), 原因: 喜好度相同, 填答資料: [10.0, nan, nan, 10.0, nan, 10.0, 10.0, 10.0, nan]
33 狀態: PASS, 平台數: 0.0, 分數計數: Counter({-1.0: 9}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
34 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 8.0: 2}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 8.0, nan, 8.0, nan]
35 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 7.0: 1, 8.0: 1}), 原因: 平台數<=2, 填答資料: [7.0, nan, nan, nan, nan, 8.0, nan, nan, nan]
36 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
37 狀態: PASS, 平台數: 4.0, 分數計數: Counter({-1.0: 5, 6.0: 2, 3.0: 1, 2.0: 1}), 原因: 不屬於任何規則, 填答資料: [3.0, nan, 2.0, nan, nan, 6.0, nan, 6.0, nan]
38 狀態: Type1, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 7.0: 3}), 原因: 喜好度相同, 填答資料: [7.0, nan, nan, nan, nan, 7.0, 7.0, nan, nan]
39 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
40 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 10.0: 2}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 10.0, nan, 10.0, nan]
41 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 7.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 7.0, nan, nan, nan]
42 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
43 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 5.0: 2}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 5.0, nan, 5.0, nan]
44 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 8.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 8.0, nan, nan, nan]
45 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 10.0: 2}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 10.0, nan, 10.0, nan]
46 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
47 狀態: PASS, 平台數: 4.0, 分數計數: Counter({-1.0: 5, 8.0: 3, 6.0: 1}), 原因: 不屬於任何規則, 填答資料: [nan, 8.0, 6.0, 8.0, nan, 8.0, nan, nan, nan]
48 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 7.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 7.0, nan, nan, nan]
49 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 10.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 10.0, nan, nan, nan]
50 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 6.0: 1, 10.0: 1}), 原因: 平台數<=2, 填答資料: [6.0, nan, nan, nan, nan, 10.0, nan, nan, nan]
51 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 5.0: 2}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 5.0, nan, 5.0, nan]
52 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 0.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 0.0, nan, nan, nan]
53 狀態: Type1, 平台數: 4.0, 分數計數: Counter({-1.0: 5, 10.0: 4}), 原因: 喜好度相同, 填答資料: [10.0, nan, nan, 10.0, nan, 10.0, nan, 10.0, nan]
54 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
55 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
56 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 3.0: 1, 5.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 3.0, nan, 5.0, nan]
57 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 10.0: 2}), 原因: 平台數<=2, 填答資料: [10.0, nan, nan, nan, nan, 10.0, nan, nan, nan]
58 狀態: Type2, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 8.0: 2, 9.0: 1}), 原因: 填答間距相同, 填答資料: [8.0, nan, nan, nan, nan, 9.0, nan, 8.0, nan]
59 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
60 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 4.0: 2}), 原因: 平台數<=2, 填答資料: [4.0, nan, nan, nan, nan, 4.0, nan, nan, nan]
61 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
62 狀態: Type1, 平台數: 5.0, 分數計數: Counter({8.0: 5, -1.0: 4}), 原因: 喜好度相同, 填答資料: [8.0, nan, nan, 8.0, nan, 8.0, 8.0, 8.0, nan]
63 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
64 狀態: PASS, 平台數: 0.0, 分數計數: Counter({-1.0: 9}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
65 狀態: PASS, 平台數: 9.0, 分數計數: Counter({6.0: 4, 7.0: 2, 5.0: 2, 10.0: 1}), 原因: 不屬於任何規則, 填答資料: [7.0, 5.0, 6.0, 6.0, 5.0, 10.0, 6.0, 6.0, 7.0]
66 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 0.0: 2}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 0.0, nan, 0.0, nan]
67 狀態: Type2, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 9.0: 2, 7.0: 1}), 原因: 填答間距相同, 填答資料: [nan, nan, nan, nan, nan, 9.0, 7.0, 9.0, nan]
68 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
69 狀態: PASS, 平台數: 6.0, 分數計數: Counter({-1.0: 3, 3.0: 2, 7.0: 1, 6.0: 1, 8.0: 1, 10.0: 1}), 原因: 不屬於任何規則, 填答資料: [3.0, 7.0, nan, 6.0, nan, 8.0, 3.0, 10.0, nan]
70 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 6.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 6.0, nan, nan, nan]
71 狀態: PASS, 平台數: 0.0, 分數計數: Counter({-1.0: 9}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
72 狀態: Type1, 平台數: 5.0, 分數計數: Counter({10.0: 5, -1.0: 4}), 原因: 喜好度相同, 填答資料: [10.0, 10.0, nan, nan, 10.0, 10.0, nan, 10.0, nan]
73 狀態: PASS, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 7.0: 1, 5.0: 1, 10.0: 1}), 原因: 不屬於任何規則, 填答資料: [7.0, nan, nan, 5.0, nan, 10.0, nan, nan, nan]
74 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 0.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 0.0, nan, nan, nan]
75 狀態: Type2, 平台數: 4.0, 分數計數: Counter({-1.0: 5, 10.0: 2, 7.0: 2}), 原因: 填答間距相同, 填答資料: [10.0, nan, nan, 7.0, nan, 10.0, 7.0, nan, nan]
76 狀態: PASS, 平台數: 0.0, 分數計數: Counter({-1.0: 9}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
77 狀態: PASS, 平台數: 4.0, 分數計數: Counter({-1.0: 5, 10.0: 2, 8.0: 1, 5.0: 1}), 原因: 不屬於任何規則, 填答資料: [8.0, nan, nan, 5.0, nan, 10.0, nan, 10.0, nan]
78 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 6.0: 1, 8.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 6.0, nan, 8.0, nan]
79 狀態: PASS, 平台數: 0.0, 分數計數: Counter({-1.0: 9}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
80 狀態: PASS, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 7.0: 2, 6.0: 1}), 原因: 不屬於任何規則, 填答資料: [6.0, nan, nan, nan, nan, 7.0, nan, 7.0, nan]
81 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 9.0: 1, 10.0: 1}), 原因: 平台數<=2, 填答資料: [9.0, nan, nan, nan, nan, 10.0, nan, nan, nan]
82 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 8.0: 2}), 原因: 平台數<=2, 填答資料: [8.0, nan, nan, nan, nan, 8.0, nan, nan, nan]
83 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
84 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
85 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 8.0: 2}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 8.0, nan, 8.0, nan]
86 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 8.0: 2}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 8.0, nan, 8.0, nan]
87 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 7.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 7.0, nan, nan, nan]
88 狀態: PASS, 平台數: 5.0, 分數計數: Counter({-1.0: 4, 9.0: 2, 7.0: 1, 8.0: 1, 5.0: 1}), 原因: 不屬於任何規則, 填答資料: [nan, nan, nan, 9.0, 7.0, 9.0, 8.0, 5.0, nan]
89 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 8.0: 1, 9.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 8.0, nan, 9.0, nan]
90 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 9.0: 1, 10.0: 1}), 原因: 平台數<=2, 填答資料: [9.0, nan, nan, nan, nan, 10.0, nan, nan, nan]
91 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
92 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 9.0: 2}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, 9.0, nan, 9.0, nan, nan]
93 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
94 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 10.0: 1}), 原因: 平台數<=2, 填答資料: [10.0, nan, nan, nan, nan, nan, nan, nan, nan]
95 狀態: PASS, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 5.0: 1, 8.0: 1, 6.0: 1}), 原因: 不屬於任何規則, 填答資料: [5.0, nan, nan, nan, nan, 8.0, nan, 6.0, nan]
96 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 6.0: 1, 8.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 6.0, nan, 8.0, nan]
97 狀態: PASS, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 10.0: 2, 6.0: 1}), 原因: 不屬於任何規則, 填答資料: [nan, 10.0, nan, nan, nan, 10.0, nan, 6.0, nan]
98 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 6.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 6.0, nan, nan, nan]
99 狀態: PASS, 平台數: 4.0, 分數計數: Counter({-1.0: 5, 8.0: 1, 9.0: 1, 10.0: 1, 7.0: 1}), 原因: 不屬於任何規則, 填答資料: [8.0, nan, nan, 9.0, nan, 10.0, nan, 7.0, nan]
100 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
101 狀態: PASS, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 8.0: 2, 6.0: 1}), 原因: 不屬於任何規則, 填答資料: [8.0, nan, nan, nan, nan, 8.0, nan, 6.0, nan]
102 狀態: PASS, 平台數: 5.0, 分數計數: Counter({-1.0: 4, 0.0: 4, 2.0: 1}), 原因: 不屬於任何規則, 填答資料: [nan, nan, 0.0, 0.0, nan, 0.0, nan, 2.0, 0.0]
103 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 5.0: 2}), 原因: 平台數<=2, 填答資料: [5.0, nan, nan, nan, nan, 5.0, nan, nan, nan]
104 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 5.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 5.0, nan, nan, nan]
105 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 7.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, nan, nan, 7.0, nan]
106 狀態: Type2, 平台數: 4.0, 分數計數: Counter({-1.0: 5, 6.0: 2, 10.0: 2}), 原因: 填答間距相同, 填答資料: [6.0, nan, nan, nan, nan, 10.0, 6.0, 10.0, nan]
107 狀態: PASS, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 7.0: 1, 8.0: 1, 5.0: 1}), 原因: 不屬於任何規則, 填答資料: [7.0, nan, nan, nan, nan, 8.0, nan, 5.0, nan]
108 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 8.0: 1, 7.0: 1}), 原因: 平台數<=2, 填答資料: [8.0, nan, nan, nan, nan, 7.0, nan, nan, nan]
109 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 8.0: 2}), 原因: 平台數<=2, 填答資料: [8.0, nan, nan, nan, nan, 8.0, nan, nan, nan]
110 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
111 狀態: Type1, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 6.0: 3}), 原因: 喜好度相同, 填答資料: [6.0, nan, nan, nan, nan, 6.0, nan, 6.0, nan]
112 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 0.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, nan, 0.0, nan, nan]
113 狀態: PASS, 平台數: 4.0, 分數計數: Counter({-1.0: 5, 6.0: 1, 8.0: 1, 10.0: 1, 7.0: 1}), 原因: 不屬於任何規則, 填答資料: [6.0, nan, nan, 8.0, nan, 10.0, nan, 7.0, nan]
114 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 9.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 9.0, nan, nan, nan]
115 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 0.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 0.0, nan, nan, nan]
116 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 7.0: 1}), 原因: 平台數<=2, 填答資料: [7.0, nan, nan, nan, nan, nan, nan, nan, nan]
117 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 5.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 5.0, nan, nan, nan]
118 狀態: PASS, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 4.0: 1, 8.0: 1, 6.0: 1}), 原因: 不屬於任何規則, 填答資料: [4.0, nan, nan, nan, nan, 8.0, nan, 6.0, nan]
119 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 7.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 7.0, nan, nan, nan]
120 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 9.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 9.0, nan, nan, nan]
121 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 7.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 7.0, nan, nan, nan]
122 狀態: PASS, 平台數: 7.0, 分數計數: Counter({10.0: 4, -1.0: 2, 5.0: 1, 7.0: 1, 9.0: 1}), 原因: 不屬於任何規則, 填答資料: [5.0, nan, 10.0, 10.0, 10.0, 7.0, 9.0, 10.0, nan]
123 狀態: Type1, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 10.0: 3}), 原因: 喜好度相同, 填答資料: [10.0, nan, nan, nan, nan, 10.0, nan, 10.0, nan]
124 狀態: PASS, 平台數: 4.0, 分數計數: Counter({-1.0: 5, 8.0: 2, 9.0: 1, 10.0: 1}), 原因: 不屬於任何規則, 填答資料: [nan, nan, nan, 8.0, nan, 8.0, 9.0, 10.0, nan]
125 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
126 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 10.0: 2}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 10.0, nan, 10.0, nan]
127 狀態: Type1, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 10.0: 3}), 原因: 喜好度相同, 填答資料: [10.0, nan, nan, nan, nan, 10.0, nan, 10.0, nan]
128 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 2.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 2.0, nan, nan, nan]
129 狀態: PASS, 平台數: 9.0, 分數計數: Counter({1.0: 6, 3.0: 1, 10.0: 1, 2.0: 1}), 原因: 不屬於任何規則, 填答資料: [1.0, 1.0, 1.0, 1.0, 3.0, 10.0, 1.0, 2.0, 1.0]
130 狀態: Type2, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 8.0: 2, 9.0: 1}), 原因: 填答間距相同, 填答資料: [8.0, nan, nan, nan, nan, 9.0, nan, 8.0, nan]
131 狀態: PASS, 平台數: 5.0, 分數計數: Counter({-1.0: 4, 0.0: 2, 2.0: 1, 10.0: 1, 3.0: 1}), 原因: 不屬於任何規則, 填答資料: [2.0, 10.0, nan, nan, nan, 0.0, 3.0, 0.0, nan]
132 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 9.0: 1, 8.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 9.0, nan, 8.0, nan]
133 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 7.0: 1, 9.0: 1}), 原因: 平台數<=2, 填答資料: [7.0, nan, nan, nan, nan, 9.0, nan, nan, nan]
134 狀態: PASS, 平台數: 3.0, 分數計數: Counter({-1.0: 6, 10.0: 2, 0.0: 1}), 原因: 不屬於任何規則, 填答資料: [0.0, nan, nan, nan, nan, 10.0, nan, 10.0, nan]
135 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 6.0: 1, 10.0: 1}), 原因: 平台數<=2, 填答資料: [6.0, nan, nan, nan, nan, 10.0, nan, nan, nan]
136 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
137 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
138 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 6.0: 2}), 原因: 平台數<=2, 填答資料: [6.0, nan, nan, nan, nan, 6.0, nan, nan, nan]
139 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 10.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, nan, nan, 10.0, nan]
140 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
141 狀態: PASS, 平台數: 0.0, 分數計數: Counter({-1.0: 9}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
142 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
143 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 7.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 7.0, nan, nan, nan]
144 狀態: Type1, 平台數: 4.0, 分數計數: Counter({-1.0: 5, 0.0: 4}), 原因: 喜好度相同, 填答資料: [0.0, nan, nan, 0.0, nan, 0.0, nan, 0.0, nan]
145 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 9.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 9.0, nan, nan, nan]
146 狀態: PASS, 平台數: 4.0, 分數計數: Counter({-1.0: 5, 6.0: 1, 3.0: 1, 10.0: 1, 5.0: 1}), 原因: 不屬於任何規則, 填答資料: [6.0, nan, nan, 3.0, nan, 10.0, 5.0, nan, nan]
147 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 7.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 7.0, nan, nan, nan]
148 狀態: PASS, 平台數: 0.0, 分數計數: Counter({-1.0: 9}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
149 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
150 狀態: PASS, 平台數: 0.0, 分數計數: Counter({-1.0: 9}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
151 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 5.0: 1, 8.0: 1}), 原因: 平台數<=2, 填答資料: [5.0, nan, nan, nan, nan, 8.0, nan, nan, nan]
152 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 9.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 9.0, nan, nan, nan]
153 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 8.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 8.0, nan, nan, nan]
154 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 10.0: 1, 8.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 10.0, nan, 8.0, nan]
155 狀態: PASS, 平台數: 2.0, 分數計數: Counter({-1.0: 7, 7.0: 2}), 原因: 平台數<=2, 填答資料: [7.0, nan, nan, nan, nan, 7.0, nan, nan, nan]
156 狀態: Nan, 平台數: nan, 分數計數: Counter({-1.0: 9}), 原因: 平台數==Nan, 填答資料: [nan, nan, nan, nan, nan, nan, nan, nan, nan]
157 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 9.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 9.0, nan, nan, nan]
158 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 8.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 8.0, nan, nan, nan]
159 狀態: PASS, 平台數: 1.0, 分數計數: Counter({-1.0: 8, 8.0: 1}), 原因: 平台數<=2, 填答資料: [nan, nan, nan, nan, nan, 8.0, nan, nan, nan]

,q0063_0001,q0063_0002,q0063_0003,q0063_0004,q0063_0005,q0063_0006,q0063_0007,q0063_0008,q0063_0009,Status
0,5.0,NaN,NaN,NaN,NaN,5.0,NaN,NaN,NaN,PASS
1,7.0,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,PASS
2,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,PASS
3,5.0,NaN,NaN,NaN,NaN,10.0,8.0,NaN,NaN,PASS
4,5.0,NaN,NaN,8.0,NaN,10.0,NaN,8.0,NaN,PASS
...,...,...,...,...,...,...,...,...,...,...
218,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,PASS
219,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,PASS
220,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,PASS
221,9.0,NaN,NaN,NaN,NaN,9.0,NaN,9.0,NaN,Type1
222,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,PASS

3.	因客戶希望資料的可讀性更高，所以希望能修正第61題的填答狀況。
Q3. 如該受訪者未作答第61題，則每個選項的填答結果仍維持為#N/A。
如果該受訪者有作答第61題，則將第61題中每個選項的填答結果依下述規則修正：
1: 有勾選該選項
0: 沒有勾選該選項

In [127]:
for i in range(len(question_61)):
  if not np.isnan(question_61['B2_Count'].iloc[i]):
    question_61.iloc[i, :-1] = question_61.iloc[i, :-1].fillna(0)
question_61.head(50)

,q0061_0001,q0061_0002,q0061_0003,q0061_0004,q0061_0005,q0061_0006,q0061_0007,q0061_0008,q0061_0009,q0061_0010,B2_Count
0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0
1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0
4,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,4.0
5,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,3.0
6,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
8,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0
9,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
10,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0
11,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
12,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0
13,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
14,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0
15,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0
17,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,3.0
18,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0
19,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,4.0
20,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0
21,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0
22,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0
23,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0
24,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0
25,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
29,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,3.0
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
32,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,5.0
33,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0
35,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,4.0
38,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0
41,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0
44,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
45,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,4.0
48,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
49,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

檔案繳交規定
請將Email, B2_Count, Status和修正完的第61題輸出成一張Excel表，並將檔案命名依此格式命名：{NAME} _TNL Data Analyst Intern_test3_R_output.xlsx
程式碼請命名為：{NAME} _TNL Data Analyst Intern_test3_R_code.R

,CollectorNm,RespondentID,CollectorID,StartDate,EndDate,Email,q0001,q0002,q0003,q0004,...,q0090_0002,q0090_0003,q0090_0004,q0090_0005,q0090_0006,q0090_0007,q0090_0008,q0090_0009,q0090_0010,q0091
0,Web Link 1,118216343540,447807947,01/11/2023 12:13:43 AM,01/11/2023 12:26:35 AM,5e5612f634ea77b56c818312d0d2a8c5,2,42.0,4.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Web Link 1,118216198616,447807947,01/10/2023 09:11:22 PM,01/10/2023 09:21:49 PM,c09b092ac26cc501bf26e9f7b094b188,1,75.0,1.0,9.0,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,40.0,1.0
2,Web Link 1,118215238755,447807947,01/09/2023 03:03:40 PM,01/09/2023 03:08:54 PM,7e18569b0d74a3e0e9f3ac11ce97c73a,2,43.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,Web Link 1,118214918707,447807947,01/08/2023 07:08:42 PM,01/08/2023 07:24:13 PM,f5d1d383072167bcd46481152eb6bb81,1,60.0,7.0,14.0,...,0.0,NaN,65.0,NaN,NaN,NaN,30.0,NaN,NaN,1.0
4,Web Link 1,118214660644,447807947,01/07/2023 11:32:52 PM,01/07/2023 11:47:46 PM,c76ed234a1b3e4e04de917979e2e8c64,1,48.0,5.0,8.0,...,0.0,NaN,85.0,NaN,NaN,NaN,5.0,NaN,5.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,Web Link 1,118157890426,447807947,10/25/2022 01:14:40 AM,10/25/2022 01:17:33 AM,d66ac0ff916072660a6569c74b4c455f,3,22.0,9.0,12.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
219,Web Link 1,118157877427,447807947,10/25/2022 01:01:36 AM,10/25/2022 01:06:47 AM,5de3ccde542bfaa3e24b1dca7ab77af9,2,32.0,6.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
220,Web Link 1,118157723237,447807947,10/24/2022 10:10:18 PM,10/24/2022 10:14:46 PM,20afabe98a15a4946561e9a37c7b33fd,1,37.0,12.0,18.0,...,NaN,NaN,40.0,NaN,NaN,NaN,60.0,NaN,NaN,NaN
221,Web Link 1,118157556636,447807947,10/24/2022 05:29:39 PM,10/24/2022 05:41:06 PM,bc878c1cad2f684d48b765c7d2d2eca5,1,50.0,6.0,15.0,...,NaN,NaN,60.0,NaN,NaN,NaN,20.0,0.0,NaN,1.0
222,Web Link 1,118157494480,447807947,10/24/2022 02:52:42 PM,10/24/2022 02:58:10 PM,2f3acab6e9317a6baaa26fe85898956a,1,22.0,2.0,20.0,...,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,NaN,1.0

In [139]:
df_toExcel = question_61
df_toExcel["Email"] = RAW_DATA["Email"]
df_toExcel["Status"] = question_63["Status"]
order = ['Email', 'B2_Count', 'Status','q0061_0001', 'q0061_0002', 'q0061_0003', 'q0061_0004', 'q0061_0005','q0061_0006', 'q0061_0007', 'q0061_0008', 'q0061_0009', 'q0061_0010']
df_toExcel = df_toExcel[order]
df_toExcel

,Email,B2_Count,Status,q0061_0001,q0061_0002,q0061_0003,q0061_0004,q0061_0005,q0061_0006,q0061_0007,q0061_0008,q0061_0009,q0061_0010
0,5e5612f634ea77b56c818312d0d2a8c5,2.0,PASS,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,c09b092ac26cc501bf26e9f7b094b188,2.0,PASS,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,7e18569b0d74a3e0e9f3ac11ce97c73a,1.0,PASS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,f5d1d383072167bcd46481152eb6bb81,3.0,PASS,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,c76ed234a1b3e4e04de917979e2e8c64,4.0,PASS,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,d66ac0ff916072660a6569c74b4c455f,1.0,PASS,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
219,5de3ccde542bfaa3e24b1dca7ab77af9,1.0,PASS,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
220,20afabe98a15a4946561e9a37c7b33fd,1.0,PASS,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
221,bc878c1cad2f684d48b765c7d2d2eca5,3.0,Type1,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
222,2f3acab6e9317a6baaa26fe85898956a,2.0,PASS,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [140]:
df_toExcel.to_excel("謝天青_TNL Data Analyst Intern_test3_R_output.xlsx", encoding = "utf-8")